"""Transaction flags (tf*/asf*) and ledger-entry flags (lsf*) from xahaud.

Auto-generated from include/xrpl/protocol/TxFlags.h, include/xrpl/protocol/LedgerFormats.h.
Source: xahaud @ bb244ef77
Regenerate: python scripts/gen-constants.py <xahaud-root>

Every constant carries its origin in the repo's citation
convention — `xahaud:<path>:<line>` names the exact line of the
pinned xahaud tree it was read from.
"""

# ---- UniversalFlags (include/xrpl/protocol/TxFlags.h) ----
tfFullyCanonicalSig = 0x80000000  # xahaud:include/xrpl/protocol/TxFlags.h:61
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfUniversal = 0x80000000  # xahaud:include/xrpl/protocol/TxFlags.h:63
tfUniversalMask = 0x7FFFFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:64
# ---- AccountSetFlags (include/xrpl/protocol/TxFlags.h) ----
tfRequireDestTag = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:68
tfOptionalDestTag = 0x00020000  # xahaud:include/xrpl/protocol/TxFlags.h:69
tfRequireAuth = 0x00040000  # xahaud:include/xrpl/protocol/TxFlags.h:70
tfOptionalAuth = 0x00080000  # xahaud:include/xrpl/protocol/TxFlags.h:71
tfDisallowXRP = 0x00100000  # xahaud:include/xrpl/protocol/TxFlags.h:72
tfAllowXRP = 0x00200000  # xahaud:include/xrpl/protocol/TxFlags.h:73
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfAccountSetMask = 0x7FC0FFFF  # xahaud:include/xrpl/protocol/TxFlags.h:75
# ---- AccountFlags (include/xrpl/protocol/TxFlags.h) ----
asfRequireDest = 1  # xahaud:include/xrpl/protocol/TxFlags.h:81
asfRequireAuth = 2  # xahaud:include/xrpl/protocol/TxFlags.h:82
asfDisallowXRP = 3  # xahaud:include/xrpl/protocol/TxFlags.h:83
asfDisableMaster = 4  # xahaud:include/xrpl/protocol/TxFlags.h:84
asfAccountTxnID = 5  # xahaud:include/xrpl/protocol/TxFlags.h:85
asfNoFreeze = 6  # xahaud:include/xrpl/protocol/TxFlags.h:86
asfGlobalFreeze = 7  # xahaud:include/xrpl/protocol/TxFlags.h:87
asfDefaultRipple = 8  # xahaud:include/xrpl/protocol/TxFlags.h:88
asfDepositAuth = 9  # xahaud:include/xrpl/protocol/TxFlags.h:89
asfAuthorizedNFTokenMinter = 10  # xahaud:include/xrpl/protocol/TxFlags.h:90
asfTshCollect = 11  # xahaud:include/xrpl/protocol/TxFlags.h:91
asfDisallowIncomingNFTokenOffer = 12  # xahaud:include/xrpl/protocol/TxFlags.h:92
asfDisallowIncomingCheck = 13  # xahaud:include/xrpl/protocol/TxFlags.h:93
asfDisallowIncomingPayChan = 14  # xahaud:include/xrpl/protocol/TxFlags.h:94
asfDisallowIncomingTrustline = 15  # xahaud:include/xrpl/protocol/TxFlags.h:95
asfDisallowIncomingRemit = 16  # xahaud:include/xrpl/protocol/TxFlags.h:96
asfAllowTrustLineClawback = 17  # xahaud:include/xrpl/protocol/TxFlags.h:97
# ---- OfferCreateFlags (include/xrpl/protocol/TxFlags.h) ----
tfPassive = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:102
tfImmediateOrCancel = 0x00020000  # xahaud:include/xrpl/protocol/TxFlags.h:103
tfFillOrKill = 0x00040000  # xahaud:include/xrpl/protocol/TxFlags.h:104
tfSell = 0x00080000  # xahaud:include/xrpl/protocol/TxFlags.h:105
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfOfferCreateMask = 0x7FF0FFFF  # xahaud:include/xrpl/protocol/TxFlags.h:107
# ---- PaymentFlags (include/xrpl/protocol/TxFlags.h) ----
tfNoRippleDirect = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:112
tfPartialPayment = 0x00020000  # xahaud:include/xrpl/protocol/TxFlags.h:113
tfLimitQuality = 0x00040000  # xahaud:include/xrpl/protocol/TxFlags.h:114
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfPaymentMask = 0x7FF8FFFF  # xahaud:include/xrpl/protocol/TxFlags.h:116
tfMPTPaymentMask = 0x7FFDFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:118
# ---- TrustSetFlags (include/xrpl/protocol/TxFlags.h) ----
tfSetfAuth = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:122
tfSetNoRipple = 0x00020000  # xahaud:include/xrpl/protocol/TxFlags.h:123
tfClearNoRipple = 0x00040000  # xahaud:include/xrpl/protocol/TxFlags.h:124
tfSetFreeze = 0x00100000  # xahaud:include/xrpl/protocol/TxFlags.h:125
tfClearFreeze = 0x00200000  # xahaud:include/xrpl/protocol/TxFlags.h:126
tfSetDeepFreeze = 0x00400000  # xahaud:include/xrpl/protocol/TxFlags.h:127
tfClearDeepFreeze = 0x00800000  # xahaud:include/xrpl/protocol/TxFlags.h:128
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfTrustSetMask = 0x7F08FFFF  # xahaud:include/xrpl/protocol/TxFlags.h:130
# ---- EnableAmendmentFlags (include/xrpl/protocol/TxFlags.h) ----
tfGotMajority = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:136
tfLostMajority = 0x00020000  # xahaud:include/xrpl/protocol/TxFlags.h:137
tfTestSuite = 0x80000000  # xahaud:include/xrpl/protocol/TxFlags.h:138
# ---- PaymentChannelClaimFlags (include/xrpl/protocol/TxFlags.h) ----
tfRenew = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:143
tfClose = 0x00020000  # xahaud:include/xrpl/protocol/TxFlags.h:144
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfPayChanClaimMask = 0x7FFCFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:146
# ---- NFTokenMintFlags (include/xrpl/protocol/TxFlags.h) ----
tfBurnable = 1  # xahaud:include/xrpl/protocol/TxFlags.h:150
tfOnlyXRP = 2  # xahaud:include/xrpl/protocol/TxFlags.h:151
tfTrustLine = 4  # xahaud:include/xrpl/protocol/TxFlags.h:152
tfTransferable = 8  # xahaud:include/xrpl/protocol/TxFlags.h:153
tfMutable = 16  # xahaud:include/xrpl/protocol/TxFlags.h:154
tfStrongTSH = 32768  # xahaud:include/xrpl/protocol/TxFlags.h:155
# ---- MPTokenIssuanceCreateFlags (include/xrpl/protocol/TxFlags.h) ----
tfMPTCanLock = 2  # xahaud:include/xrpl/protocol/TxFlags.h:161
tfMPTRequireAuth = 4  # xahaud:include/xrpl/protocol/TxFlags.h:162
tfMPTCanEscrow = 8  # xahaud:include/xrpl/protocol/TxFlags.h:163
tfMPTCanTrade = 16  # xahaud:include/xrpl/protocol/TxFlags.h:164
tfMPTCanTransfer = 32  # xahaud:include/xrpl/protocol/TxFlags.h:165
tfMPTCanClawback = 64  # xahaud:include/xrpl/protocol/TxFlags.h:166
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfMPTokenIssuanceCreateMask = 0x7FFFFF81  # xahaud:include/xrpl/protocol/TxFlags.h:168
# ---- MPTokenAuthorizeFlags (include/xrpl/protocol/TxFlags.h) ----
tfMPTUnauthorize = 1  # xahaud:include/xrpl/protocol/TxFlags.h:173
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfMPTokenAuthorizeMask = 0x7FFFFFFE  # xahaud:include/xrpl/protocol/TxFlags.h:175
# ---- MPTokenIssuanceSetFlags (include/xrpl/protocol/TxFlags.h) ----
tfMPTLock = 1  # xahaud:include/xrpl/protocol/TxFlags.h:179
tfMPTUnlock = 2  # xahaud:include/xrpl/protocol/TxFlags.h:180
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfMPTokenIssuanceSetMask = 0x7FFFFFFC  # xahaud:include/xrpl/protocol/TxFlags.h:182
tfMPTokenIssuanceDestroyMask = 0x7FFFFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:185
tfNFTokenMintMask = 0x7FFF7FF4  # xahaud:include/xrpl/protocol/TxFlags.h:200
tfNFTokenMintOldMask = 0x7FFF7FF0  # xahaud:include/xrpl/protocol/TxFlags.h:203
tfNFTokenMintOldMaskWithMutable = 0x7FFF7FE0  # xahaud:include/xrpl/protocol/TxFlags.h:207
tfNFTokenMintMaskWithMutable = 0x7FFF7FE4  # xahaud:include/xrpl/protocol/TxFlags.h:210
# ---- NFTokenCreateOfferFlags (include/xrpl/protocol/TxFlags.h) ----
tfSellNFToken = 1  # xahaud:include/xrpl/protocol/TxFlags.h:215
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfNFTokenCreateOfferMask = 0x7FFFFFFE  # xahaud:include/xrpl/protocol/TxFlags.h:217
tfNFTokenCancelOfferMask = 0x7FFFFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:221
tfNFTokenAcceptOfferMask = 0x7FFFFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:224
tfURITokenMintMask = 0x7FFFFFFE  # xahaud:include/xrpl/protocol/TxFlags.h:227
tfURITokenNonMintMask = 0x7FFFFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:228
# ---- ClaimRewardFlags (include/xrpl/protocol/TxFlags.h) ----
tfOptOut = 1  # xahaud:include/xrpl/protocol/TxFlags.h:232
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfClaimRewardMask = 0x7FFFFFFE  # xahaud:include/xrpl/protocol/TxFlags.h:234
tfImmutable = 1  # xahaud:include/xrpl/protocol/TxFlags.h:237
tfClawbackMask = 0x7FFFFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:240
# ---- CronSetFlags (include/xrpl/protocol/TxFlags.h) ----
tfCronUnset = 1  # xahaud:include/xrpl/protocol/TxFlags.h:244
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfCronSetMask = 0x7FFFFFFE  # xahaud:include/xrpl/protocol/TxFlags.h:246
tfLPToken = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:249
tfWithdrawAll = 0x00020000  # xahaud:include/xrpl/protocol/TxFlags.h:250
tfOneAssetWithdrawAll = 0x00040000  # xahaud:include/xrpl/protocol/TxFlags.h:251
tfSingleAsset = 0x00080000  # xahaud:include/xrpl/protocol/TxFlags.h:252
tfTwoAsset = 0x00100000  # xahaud:include/xrpl/protocol/TxFlags.h:253
tfOneAssetLPToken = 0x00200000  # xahaud:include/xrpl/protocol/TxFlags.h:254
tfLimitLPToken = 0x00400000  # xahaud:include/xrpl/protocol/TxFlags.h:255
tfTwoAssetIfEmpty = 0x00800000  # xahaud:include/xrpl/protocol/TxFlags.h:256
tfWithdrawSubTx = 0x007F0000  # xahaud:include/xrpl/protocol/TxFlags.h:257
tfDepositSubTx = 0x00F90000  # xahaud:include/xrpl/protocol/TxFlags.h:260
tfWithdrawMask = 0x7F80FFFF  # xahaud:include/xrpl/protocol/TxFlags.h:263
tfDepositMask = 0x7F06FFFF  # xahaud:include/xrpl/protocol/TxFlags.h:264
# ---- AMMClawbackFlags (include/xrpl/protocol/TxFlags.h) ----
tfClawTwoAssets = 1  # xahaud:include/xrpl/protocol/TxFlags.h:268
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfAMMClawbackMask = 0x7FFFFFFE  # xahaud:include/xrpl/protocol/TxFlags.h:270
# ---- BridgeModifyFlags (include/xrpl/protocol/TxFlags.h) ----
tfClearAccountCreateAmount = 0x00010000  # xahaud:include/xrpl/protocol/TxFlags.h:274
# ---- constexpr (include/xrpl/protocol/TxFlags.h) ----
tfBridgeModifyMask = 0x7FFEFFFF  # xahaud:include/xrpl/protocol/TxFlags.h:276

# ---- LedgerEntryType (include/xrpl/protocol/LedgerFormats.h) ----
value = 0  # xahaud:include/xrpl/protocol/LedgerFormats.h:59
name = 1  # xahaud:include/xrpl/protocol/LedgerFormats.h:59
rpcName = 2  # xahaud:include/xrpl/protocol/LedgerFormats.h:59
fields = 0  # xahaud:include/xrpl/protocol/LedgerFormats.h:59
ltANY = 0  # xahaud:include/xrpl/protocol/LedgerFormats.h:78
ltCHILD = 7378  # xahaud:include/xrpl/protocol/LedgerFormats.h:91
ltNICKNAME = 7379  # xahaud:include/xrpl/protocol/LedgerFormats.h:100
# ---- LedgerSpecificFlags (include/xrpl/protocol/LedgerFormats.h) ----
lsfPasswordSpent = 0x00010000  # xahaud:include/xrpl/protocol/LedgerFormats.h:125
lsfRequireDestTag = 0x00020000  # xahaud:include/xrpl/protocol/LedgerFormats.h:126
lsfRequireAuth = 0x00040000  # xahaud:include/xrpl/protocol/LedgerFormats.h:128
lsfDisallowXRP = 0x00080000  # xahaud:include/xrpl/protocol/LedgerFormats.h:130
lsfDisableMaster = 0x00100000  # xahaud:include/xrpl/protocol/LedgerFormats.h:131
lsfNoFreeze = 0x00200000  # xahaud:include/xrpl/protocol/LedgerFormats.h:132
lsfGlobalFreeze = 0x00400000  # xahaud:include/xrpl/protocol/LedgerFormats.h:133
lsfDefaultRipple = 0x00800000  # xahaud:include/xrpl/protocol/LedgerFormats.h:134
lsfDepositAuth = 0x01000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:136
lsfTshCollect = 0x02000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:137
lsfDisallowIncomingNFTokenOffer = 0x04000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:138
lsfDisallowIncomingCheck = 0x08000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:140
lsfDisallowIncomingPayChan = 0x10000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:142
lsfDisallowIncomingTrustline = 0x20000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:144
lsfURITokenIssuer = 0x40000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:146
lsfDisallowIncomingRemit = 0x80000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:148
lsfAllowTrustLineClawback = 4096  # xahaud:include/xrpl/protocol/LedgerFormats.h:151
lsfPassive = 0x00010000  # xahaud:include/xrpl/protocol/LedgerFormats.h:155
lsfSell = 0x00020000  # xahaud:include/xrpl/protocol/LedgerFormats.h:156
lsfLowReserve = 0x00010000  # xahaud:include/xrpl/protocol/LedgerFormats.h:159
lsfHighReserve = 0x00020000  # xahaud:include/xrpl/protocol/LedgerFormats.h:160
lsfLowAuth = 0x00040000  # xahaud:include/xrpl/protocol/LedgerFormats.h:161
lsfHighAuth = 0x00080000  # xahaud:include/xrpl/protocol/LedgerFormats.h:162
lsfLowNoRipple = 0x00100000  # xahaud:include/xrpl/protocol/LedgerFormats.h:163
lsfHighNoRipple = 0x00200000  # xahaud:include/xrpl/protocol/LedgerFormats.h:164
lsfLowFreeze = 0x00400000  # xahaud:include/xrpl/protocol/LedgerFormats.h:165
lsfHighFreeze = 0x00800000  # xahaud:include/xrpl/protocol/LedgerFormats.h:166
lsfLowDeepFreeze = 0x02000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:167
lsfHighDeepFreeze = 0x04000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:168
lsfAMMNode = 0x01000000  # xahaud:include/xrpl/protocol/LedgerFormats.h:169
lsfOneOwnerCount = 0x00010000  # xahaud:include/xrpl/protocol/LedgerFormats.h:173
lsfNFTokenBuyOffers = 1  # xahaud:include/xrpl/protocol/LedgerFormats.h:176
lsfNFTokenSellOffers = 2  # xahaud:include/xrpl/protocol/LedgerFormats.h:177
lsfEmittedDir = 4  # xahaud:include/xrpl/protocol/LedgerFormats.h:178
lsfSellNFToken = 1  # xahaud:include/xrpl/protocol/LedgerFormats.h:181
lsfBurnable = 1  # xahaud:include/xrpl/protocol/LedgerFormats.h:184
lsfImmutable = 1  # xahaud:include/xrpl/protocol/LedgerFormats.h:187
lsfMPTLocked = 1  # xahaud:include/xrpl/protocol/LedgerFormats.h:190
lsfMPTCanLock = 2  # xahaud:include/xrpl/protocol/LedgerFormats.h:191
lsfMPTRequireAuth = 4  # xahaud:include/xrpl/protocol/LedgerFormats.h:192
lsfMPTCanEscrow = 8  # xahaud:include/xrpl/protocol/LedgerFormats.h:193
lsfMPTCanTrade = 16  # xahaud:include/xrpl/protocol/LedgerFormats.h:194
lsfMPTCanTransfer = 32  # xahaud:include/xrpl/protocol/LedgerFormats.h:195
lsfMPTCanClawback = 64  # xahaud:include/xrpl/protocol/LedgerFormats.h:196
lsfMPTAuthorized = 2  # xahaud:include/xrpl/protocol/LedgerFormats.h:199
lsfAccepted = 0x00010000  # xahaud:include/xrpl/protocol/LedgerFormats.h:202
